                
  version: '3.3'                                                                                                                     
                                                                                                                                      
  services:
    postgres:                                                                                                                         
      image: postgres:16
      container_name: knitshop-db
      environment:
        POSTGRES_DB: knitshop
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:                                                                                                                          
        - "5432:5432"
      volumes:                                                                                                                        
        - knitshop-data:/var/lib/postgresql/data

  volumes:
    knitshop-data:
